export const UNIVERSITIES = [
    { value: 'UG', label: 'University of Ghana' },
    { value: 'KNUST', label: 'Kwame Nkrumah University of Science and Technology' },
    { value: 'UCC', label: 'University of Cape Coast' },
    { value: 'UEW', label: 'University of Education, Winneba' },
    { value: 'UDS', label: 'University for Development Studies' },
    { value: 'UPSA', label: 'University of Professional Studies, Accra' },
    { value: 'UMAT', label: 'University of Mines and Technology' },
    { value: 'UHAS', label: 'University of Health and Allied Sciences' },
    { value: 'UENR', label: 'University of Energy and Natural Resources' },
    { value: 'GIMPA', label: 'Ghana Institute of Management and Public Administration' },
    { value: 'GCTU', label: 'Ghana Communication Technology University' },
    { value: 'AAMUSTED', label: 'Akenten Appiah-Menka University of Skills Training and Entrepreneurial Development' },
    { value: 'CKT_UTAS', label: 'C. K. Tedam University of Technology and Applied Sciences' },
    { value: 'SDD_UBIDS', label: 'Simon Diedong Dombo University of Business and Integrated Development Studies' },
    { value: 'ASHESI', label: 'Ashesi University' },
    { value: 'CENTRAL', label: 'Central University' },
    { value: 'VALLEY_VIEW', label: 'Valley View University' },
    { value: 'PENTECOST', label: 'Pentecost University' },
    { value: 'WISCONSIN', label: 'Wisconsin International University College' },
    { value: 'METHODIST', label: 'Methodist University Ghana' },
    { value: 'PRESBYTERIAN', label: 'Presbyterian University, Ghana' },
    { value: 'ACADEMIC_CITY', label: 'Academic City University College' },
    { value: 'LANCASTER', label: 'Lancaster University Ghana' },
    { value: 'WEBSTER', label: 'Webster University Ghana' },
    { value: 'AUCC', label: 'African University College of Communications' },
    { value: 'STU', label: 'Sunyani Technical University' },
    { value: 'TTU', label: 'Takoradi Technical University' },
    { value: 'HTU', label: 'Ho Technical University' },
    { value: 'KTU', label: 'Koforidua Technical University' },
    { value: 'KsTU', label: 'Kumasi Technical University' },
    { value: 'ATU', label: 'Accra Technical University' },
    { value: 'OTHER', label: 'Other' },
];

export const ACADEMIC_LEVELS = [
    { value: 'LEVEL_100', label: 'Level 100' },
    { value: 'LEVEL_200', label: 'Level 200' },
    { value: 'LEVEL_300', label: 'Level 300' },
    { value: 'LEVEL_400', label: 'Level 400' },
    { value: 'LEVEL_500', label: 'Level 500' },
    { value: 'LEVEL_600', label: 'Level 600' },
    { value: 'GRADUATE', label: 'Graduate Student' },
];

export const REFERRAL_SOURCES = [
    { value: 'SOCIAL_MEDIA', label: 'Social Media (Facebook, Instagram, etc.)' },
    { value: 'WHATSAPP', label: 'WhatsApp' },
    { value: 'FRIEND_OR_COLLEAGUE', label: 'Friend or Colleague' },
    { value: 'UNIVERSITY_NOTICE', label: 'University Notice Board/Announcement' },
    { value: 'EMAIL', label: 'Email' },
    { value: 'WEBSITE', label: 'Website/Blog' },
    { value: 'FLYER_POSTER', label: 'Flyer/Poster' },
    { value: 'RADIO', label: 'Radio' },
    { value: 'CHURCH_FELLOWSHIP', label: 'Church/Fellowship' },
    { value: 'PREVIOUS_EVENT', label: 'Attended Previous Event' },
    { value: 'SPEAKER_RECOMMENDATION', label: 'Speaker Recommendation' },
    { value: 'DEPARTMENT_FACULTY', label: 'Department/Faculty' },
    { value: 'STUDENT_ORGANIZATION', label: 'Student Organization' },
    { value: 'OTHER', label: 'Other' },
];
export const SHIRT_SIZES = [
    { value: 'XS', label: 'Extra Small' },
    { value: 'S', label: 'Small' },
    { value: 'M', label: 'Medium' },
    { value: 'L', label: 'Large' },
    { value: 'XL', label: 'Extra Large' },
    { value: 'XXL', label: '2X Large' },
    { value: 'XXXL', label: '3X Large' },
];

export const SHIRT_COLORS = [
    { value: 'BLACK', label: 'Black' },
    { value: 'WHITE', label: 'White' },
];
